---
title: Compare characteristics of network consenting vs non-consenting participants
output: html_document
date: "2023-01-15"
editor_options: 
  markdown: 
    wrap: 72
---

```{r, setup, include=FALSE}
rm(list=ls())
library(dplyr)
```

```{r, data_loc, include=FALSE}
data_loc <- "/Volumes/caas/CADRE CLC Data Project5/Clean Data/AK-SU-NETWORKS-ROUT/"
```


```{r}
tab2_dt <- as.data.frame(readRDS(paste0(data_loc, "tab2_comparison_data.RDS")))
class(tab2_dt)
dim(tab2_dt)
colnames(tab2_dt)

eda_env <- readRDS(paste0(data_loc, "eda_objects.rds"))
cdc_scores <- eda_env$cdc_scores
```

Compare `FUSNCONSENT == 7` vs not. 

Recode NA is FUSNCONSENT as 0 for easier comparison

'FUSNCONSENT == 7` -- consent
'FUSNCONSENT == 0` -- not consent

```{r}
tab2_dt <- 
  tab2_dt %>% mutate(FUSNCONSENT_numeric = 
                     ifelse(is.na(FUSNCONSENT), 0, FUSNCONSENT))
```

```{r}
total_fusconsent_7 = sum(tab2_dt$FUSNCONSENT_numeric == 7)
total_fusconsent_7
total_fusconsent_0 = sum(tab2_dt$FUSNCONSENT_numeric == 0)
total_fusconsent_0

t.test(as.numeric(tab2_dt$age[tab2_dt$FUSNCONSENT_numeric == 7]),
       as.numeric(tab2_dt$age[tab2_dt$FUSNCONSENT_numeric == 0])
       )


table(tab2_dt$gender_3cat)

```

## Test Differences

### Age
```{r}
stats_age <- tab2_dt %>%
  mutate(age_numeric = as.numeric(as.character(age))) %>%  # Convert age to numeric
  group_by(FUSNCONSENT_numeric) %>%
  summarise(
    mean_age = mean(age_numeric, na.rm = TRUE),
    sd_age = sd(age_numeric, na.rm = TRUE)
  )

print(stats_age)

```

```{r}
# Convert age to numeric
tab2_dt$age_numeric <- as.numeric(as.character(tab2_dt$age))

# Split data based on FUSNCONSENT_numeric
group1 <- tab2_dt$age_numeric[tab2_dt$FUSNCONSENT_numeric == 0]
group2 <- tab2_dt$age_numeric[tab2_dt$FUSNCONSENT_numeric == 7]

# Perform t-test
t_test_result <- t.test(group1, group2)

print(t_test_result)

```

### Gender
```{r}
  tab2_dt %>%  
  select(gender_3cat, FUSNCONSENT_numeric) %>%
  group_by(FUSNCONSENT_numeric)

gender_xtab <- 
  xtabs(~factor(tab2_dt$gender_3cat)+factor(tab2_dt$FUSNCONSENT_numeric))

chisq.test(gender_xtab)
chisq.test(gender_xtab[1:2, 1:2])
```


### Race

```{r}
# Filter the data for relevant FUSNCONSENT_numeric values
filtered_data <- tab2_dt %>% filter(FUSNCONSENT_numeric %in% c(0, 7))

# Determine the counts and percentages
race_summary <- filtered_data %>%
  group_by(FUSNCONSENT_numeric, race_4cat) %>%
  summarise(count = n()) %>%
  mutate(total = sum(count),
         percentage = (count / total) * 100) %>%
  ungroup()

print(race_summary)
```

```{r}
race_xtab <- 
  xtabs(~factor(tab2_dt$race_4cat)+factor(tab2_dt$FUSNCONSENT_numeric))

race_xtab
chisq.test(race_xtab)
chisq.test(race_xtab[c(1, 2, 4),])
```

### Ethnicity
```{r}
ethnicity_xtab <- 
  xtabs(~factor(tab2_dt$ethnicity)+factor(tab2_dt$FUSNCONSENT_numeric))

ethnicity_xtab
chisq.test(ethnicity_xtab)

# Filter the data for relevant FUSNCONSENT_numeric values
filtered_data <- tab2_dt %>% filter(FUSNCONSENT_numeric %in% c(0, 7))

# Determine the counts and percentages
ethnicity_summary <- filtered_data %>%
  group_by(FUSNCONSENT_numeric, ethnicity) %>%
  summarise(count = n()) %>%
  mutate(total = sum(count),
         percentage = (count / total) * 100) %>%
  ungroup()

print(ethnicity_summary)
```


### Education



```{r}
education_xtab <- 
  xtabs(~factor(tab2_dt$education, exclude = NULL)+
          factor(tab2_dt$FUSNCONSENT_numeric, exclude = NULL))

education_xtab
chisq.test(education_xtab)
```
Recode education:

```{r}
tab2_dt <- tab2_dt %>%
  mutate(recoded_education = case_when(
    education %in% c(1, 2) ~ "Some High School or Lower",
    education == 3 ~ "High School Completed",
    education == 4 ~ "Some College",
    TRUE ~ as.character(education)  # to capture other possible values
  ))

education_xtab <- tab2_dt %>%
  group_by(recoded_education, FUSNCONSENT_numeric) %>%
  summarise(count = n()) %>%
  group_by(FUSNCONSENT_numeric) %>%
  mutate(percentage = (count / sum(count)) * 100) %>%
  ungroup()

# Create a contingency table
contingency_table <- table(tab2_dt$recoded_education, tab2_dt$FUSNCONSENT_numeric)

# Chi-squared test
chi_squared_result <- chisq.test(contingency_table)

# Print the result
print(chi_squared_result)
```

### Income

```{r}
table(tab2_dt$income)

# Generate cross-tabulations
income_10_xtab <- xtabs(~income + FUSNCONSENT_numeric, data = filter(tab2_dt, income == "10"))
print(income_10_xtab)

income_11_xtab <- xtabs(~income + FUSNCONSENT_numeric, data = filter(tab2_dt, income == "11"))
print(income_11_xtab)

income_4_xtab <- xtabs(~income + FUSNCONSENT_numeric, data = filter(tab2_dt, income == "4"))
print(income_4_xtab)

income_5_xtab <- xtabs(~income + FUSNCONSENT_numeric, data = filter(tab2_dt, income == "5"))
print(income_5_xtab)

income_6_xtab <- xtabs(~income + FUSNCONSENT_numeric, data = filter(tab2_dt, income == "6"))
print(income_6_xtab)

income_7_xtab <- xtabs(~income + FUSNCONSENT_numeric, data = filter(tab2_dt, income == "7"))
print(income_7_xtab)

income_8_xtab <- xtabs(~income + FUSNCONSENT_numeric, data = filter(tab2_dt, income == "8"))
print(income_8_xtab)

income_9_xtab <- xtabs(~income + FUSNCONSENT_numeric, data = filter(tab2_dt, income == "9"))
print(income_9_xtab)

```

```{r}
# Filter the data for relevant FUSNCONSENT_numeric values
filtered_data <- tab2_dt %>% filter(FUSNCONSENT_numeric %in% c(0, 7))

# Determine the counts and percentages
income_summary <- filtered_data %>%
  group_by(FUSNCONSENT_numeric, income) %>%
  summarise(count = n()) %>%
  mutate(total = sum(count),
         percentage = (count / total) * 100) %>%
  ungroup()

print(income_summary)
```

```{r}
income_xtab <- 
  xtabs(~factor(tab2_dt$income)+factor(tab2_dt$FUSNCONSENT_numeric))

income_xtab
chisq.test(income_xtab)
```

### Household size
```{r}
stats_household_size <- tab2_dt %>%
  mutate(household_size_numeric = as.numeric(as.character(household_size))) %>%  # Convert household_size to numeric
  group_by(FUSNCONSENT_numeric) %>%
  summarise(
    mean_household_size = mean(household_size_numeric, na.rm = TRUE),
    sd_household_size = sd(household_size_numeric, na.rm = TRUE)
  )

print(stats_household_size)

```

```{r}
# Convert to numeric
tab2_dt$household_numeric <- as.numeric(as.character(tab2_dt$household_size))

# Split data based on FUSNCONSENT_numeric
group1 <- tab2_dt$household_numeric [tab2_dt$FUSNCONSENT_numeric == 0]
group2 <- tab2_dt$household_numeric[tab2_dt$FUSNCONSENT_numeric == 7]

# Perform t-test
t_test_result <- t.test(group1, group2)

print(t_test_result)
```

### Essential_worker
```{r}
# Filter the data for relevant FUSNCONSENT_numeric values
filtered_data <- tab2_dt %>% filter(FUSNCONSENT_numeric %in% c(0, 7))

# Determine the counts and percentages
essential_worker_summary <- filtered_data %>%
  group_by(FUSNCONSENT_numeric, essential_worker) %>%
  summarise(count = n()) %>%
  mutate(total = sum(count),
         percentage = (count / total) * 100) %>%
  ungroup()

print(essential_worker_summary)
```

```{r}
essential_worker_xtab <- 
  xtabs(~factor(tab2_dt$essential_worker)+factor(tab2_dt$FUSNCONSENT_numeric))

essential_worker_xtab
chisq.test(essential_worker_xtab)
```

### Average CDC score 

```{r}
cdc_scores <- cdc_scores %>% filter(MTURKID != "")
tab2_dt <- tab2_dt %>% filter(MTURK1 != "") # to prevent a many-to-one join issue

# Left join cdc_scores with the relevant columns from tab2_dt
cdc_scores <- cdc_scores %>%
  left_join(select(tab2_dt, MTURK1, FUSNCONSENT_numeric), 
            by = c("MTURKID" = "MTURK1"))

# Extract the cdc_scores for participants with FUSNCONSENT_numeric values of 7 and 0
cdc_avg_out_summary <- cdc_scores %>%
  group_by(FUSNCONSENT_numeric) %>%
  summarise(mean = mean(cdc_avg_out),
            sd = sd(cdc_avg_out)) 

group1 <- cdc_scores$cdc_avg_out[cdc_scores$FUSNCONSENT_numeric == 7]
group2 <- cdc_scores$cdc_avg_out[cdc_scores$FUSNCONSENT_numeric == 0]

t.test(group1, group2)
```



### COVID testing

```{r}
# Filter the data for relevant FUSNCONSENT_numeric values
filtered_data <- tab2_dt %>% filter(FUSNCONSENT_numeric %in% c(0, 7))

# Determine the counts and percentages
covid_test_summary <- filtered_data %>%
  group_by(FUSNCONSENT_numeric, covid_test) %>%
  summarise(count = n()) %>%
  mutate(total = sum(count),
         percentage = (count / total) * 100) %>%
  ungroup()

print(covid_test_summary)
```

```{r}
covid_test_xtab <- 
  xtabs(~factor(tab2_dt$covid_test)+factor(tab2_dt$FUSNCONSENT_numeric))

covid_test_xtab
chisq.test(covid_test_xtab)
```


Test for positive covid -- tab2_dt$covid_test == 1

```{r}
# Filter the data for relevant FUSNCONSENT_numeric values
filtered_data <- tab2_dt %>% filter(FUSNCONSENT_numeric %in% c(0, 7) & covid_test == 1)

# Determine the counts and percentages
covid_test_summary <- filtered_data %>%
  group_by(FUSNCONSENT_numeric, covid_test) %>%
  summarise(count = n()) %>%
  mutate(total = sum(count),
         percentage = (count / total) * 100) %>%
  ungroup()

print(covid_test_summary)

```

### Positive test result

TBD

```{r}

```

```{r}
daily_drinking_xtab <- 
  xtabs(~factor(tab2_dt$daily_drinking, exclude = NULL)+
          factor(tab2_dt$FUSNCONSENT_numeric))

daily_drinking_xtab
chisq.test(daily_drinking_xtab)
```


```{r}
daily_opioid_xtab <- 
  xtabs(~factor(tab2_dt$daily_opioid, exclude = NULL)+
          factor(tab2_dt$FUSNCONSENT_numeric))

daily_opioid_xtab
chisq.test(daily_opioid_xtab)
```


```{r}
daily_stimulant_xtab <- 
  xtabs(~factor(tab2_dt$daily_stimulant, exclude = NULL)+
          factor(tab2_dt$FUSNCONSENT_numeric))

daily_stimulant_xtab
chisq.test(daily_stimulant_xtab)
```
